# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Test"
  Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache Dependencies
        uses: actions/cache@v3.0.7
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-maven-${{ hashFiles('**/yarn.lock') }}
                
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run Unit Tests
        run: yarn test --watchAll=false --detectOpenHandles
          
